MODEL:
  TYPE: YOLOv3-tiny
  BACKBONE: darknet53
  ANCHORS: [[10,14], [23,27], [37,58], [81,82], [135,169], [344,319]]
  ANCH_MASK: [[3, 4, 5], [1, 2, 3]]
  N_CLASSES: 80
TRAIN:
  LR: 0.001
  MOMENTUM: 0.9
  DECAY: 0.0005
  BURN_IN: 1000
  MAXITER: 500000
  STEPS: (400000, 450000)
  BATCHSIZE: 32
  SUBDIVISION: 4
  IMGSIZE: 416
  LOSSTYPE: l2
  IGNORETHRE: 0.7
AUGMENTATION:
  RANDRESIZE: True
  JITTER: 0.3
  RANDOM_PLACING: True
  HUE: 0.1
  SATURATION: 1.5
  EXPOSURE: 1.5
  LRFLIP: True
  RANDOM_DISTORT: True
TEST:
  CONFTHRE: 0.8
  NMSTHRE: 0.45
  IMGSIZE: 416
NUM_GPUS: 1
